name: Nimble test
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.0'

      - name: Running the tests
        run: nimble test